### ISSUE TITLE
  "tencent::av::AVContext::CreateContext(tencent::av::AVContext::Config*)"

### ISSUE THREAD

**Issue by liuchaotclc** [zhaoyang21cn/jshow#1]
"tencent::av::AVContext::CreateContext(tencent::av::AVContext::Config*)", referenced from:
 -[MultiRoomManager avInitWithController:] in MultiRoomManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

运行ios出现这样的问题，不知道为什么

**Comment by zhaoyang21cn** [comment]
于iOS设备来说iOS的指令集有armv6、armv7、armv7s、arm64这样四种，不同型号的iOS设备使用不同的指令集，下面是各自的区别：

armv6
iPhone、iPhone 3G
iPod 1G、iPod 2G
armv7
iPhone 3GS、iPhone 4
iPod 3G、iPod 4G、iPod 5G
iPad、iPad 2、iPad 3、iPad Mini
armv7s
iPhone 5、iPhone 5C
iPad 4
arm64
iPhone 5S iPhone 6 iPhone 6Plus
iPad Air, Retina iPad Mini

需要选择合适的指令集编译运行

**Comment by qazwyw** [comment]
同出现这个错误，你光说那个指令集不同没啥用，大家都懂，你应该把项目配置到直接下过来添加上库文件就能直接跑的比较好，（腾讯官方的demo就是这样），纯属个人建议

**Comment by qazwyw** [comment]
大兄弟，是不是你自己封装的MultiRoomManager这个类里面有某些不支持64位的？

**Comment by liuchaotclc** [comment]
是因为这个版本的代码和腾讯下载的.a库版本不对应造成的

**Comment by qazwyw** [comment]
那你怎么处理的？
